[2025-05-11T04:17:57.763+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T04:17:57.814+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-11T04:17:57.827+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-11T04:17:57.828+0700] {taskinstance.py:2306} INFO - Starting attempt 7 of 7
[2025-05-11T04:17:57.850+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_lstm_dbt> on 2025-05-08 11:30:00+00:00
[2025-05-11T04:17:57.863+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bbca_lstm_prediction', 'run_lstm_dbt', 'scheduled__2025-05-08T11:30:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/stock_predictions_bbca.py', '--cfg-path', '/tmp/tmpavunfwl1']
[2025-05-11T04:17:57.867+0700] {standard_task_runner.py:91} INFO - Job 111: Subtask run_lstm_dbt
[2025-05-11T04:17:57.875+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=340) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-11T04:17:57.876+0700] {standard_task_runner.py:63} INFO - Started process 368 to run task
[2025-05-11T04:17:57.956+0700] {task_command.py:426} INFO - Running <TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [running]> on host 63831b4a45c6
[2025-05-11T04:17:58.090+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bbca_lstm_prediction' AIRFLOW_CTX_TASK_ID='run_lstm_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T11:30:00+00:00'
[2025-05-11T04:17:58.091+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T04:17:58.111+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-11T04:17:58.113+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt --select stg_stock_predictions fct_stock_predictions lstm_performance_metrics stock_prediction_dashboard']
[2025-05-11T04:17:58.134+0700] {subprocess.py:86} INFO - Output:
[2025-05-11T04:18:01.750+0700] {subprocess.py:93} INFO - [0m21:18:01  Running with dbt=1.9.4
[2025-05-11T04:18:02.177+0700] {subprocess.py:93} INFO - [0m21:18:02  Registered adapter: postgres=1.9.0
[2025-05-11T04:18:03.367+0700] {subprocess.py:93} INFO - [0m21:18:03  Found 14 models, 3 data tests, 6 sources, 434 macros
[2025-05-11T04:18:03.374+0700] {subprocess.py:93} INFO - [0m21:18:03
[2025-05-11T04:18:03.377+0700] {subprocess.py:93} INFO - [0m21:18:03  Concurrency: 4 threads (target='dev')
[2025-05-11T04:18:03.380+0700] {subprocess.py:93} INFO - [0m21:18:03
[2025-05-11T04:18:03.750+0700] {subprocess.py:93} INFO - [0m21:18:03  1 of 4 START sql view model public_staging.stg_stock_predictions ............... [RUN]
[2025-05-11T04:18:04.000+0700] {subprocess.py:93} INFO - [0m21:18:04  1 of 4 OK created sql view model public_staging.stg_stock_predictions .......... [[32mCREATE VIEW[0m in 0.24s]
[2025-05-11T04:18:04.007+0700] {subprocess.py:93} INFO - [0m21:18:04  2 of 4 START sql table model public_core.fct_stock_predictions ................. [RUN]
[2025-05-11T04:18:06.104+0700] {subprocess.py:93} INFO - [0m21:18:06  2 of 4 OK created sql table model public_core.fct_stock_predictions ............ [[32mSELECT 1[0m in 2.09s]
[2025-05-11T04:18:06.113+0700] {subprocess.py:93} INFO - [0m21:18:06  3 of 4 START sql table model public_analytics.lstm_performance_metrics ......... [RUN]
[2025-05-11T04:18:06.115+0700] {subprocess.py:93} INFO - [0m21:18:06  4 of 4 START sql table model public_analytics.stock_prediction_dashboard ....... [RUN]
[2025-05-11T04:18:06.233+0700] {subprocess.py:93} INFO - [0m21:18:06  4 of 4 ERROR creating sql table model public_analytics.stock_prediction_dashboard  [[31mERROR[0m in 0.11s]
[2025-05-11T04:18:06.235+0700] {subprocess.py:93} INFO - [0m21:18:06  3 of 4 ERROR creating sql table model public_analytics.lstm_performance_metrics  [[31mERROR[0m in 0.11s]
[2025-05-11T04:18:06.283+0700] {subprocess.py:93} INFO - [0m21:18:06
[2025-05-11T04:18:06.285+0700] {subprocess.py:93} INFO - [0m21:18:06  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 2.90 seconds (2.90s).
[2025-05-11T04:18:06.397+0700] {subprocess.py:93} INFO - [0m21:18:06
[2025-05-11T04:18:06.399+0700] {subprocess.py:93} INFO - [0m21:18:06  [31mCompleted with 2 errors, 0 partial successes, and 0 warnings:[0m
[2025-05-11T04:18:06.401+0700] {subprocess.py:93} INFO - [0m21:18:06
[2025-05-11T04:18:06.403+0700] {subprocess.py:93} INFO - [0m21:18:06    Database Error in model stock_prediction_dashboard (models/marts/analytics/stock_prediction_dashboard.sql)
[2025-05-11T04:18:06.403+0700] {subprocess.py:93} INFO -   column ld.predicted_close does not exist
[2025-05-11T04:18:06.404+0700] {subprocess.py:93} INFO -   LINE 66:         ld.predicted_close,
[2025-05-11T04:18:06.405+0700] {subprocess.py:93} INFO -                    ^
[2025-05-11T04:18:06.406+0700] {subprocess.py:93} INFO -   compiled code at target/run/idx_stock/models/marts/analytics/stock_prediction_dashboard.sql
[2025-05-11T04:18:06.406+0700] {subprocess.py:93} INFO - [0m21:18:06
[2025-05-11T04:18:06.407+0700] {subprocess.py:93} INFO - [0m21:18:06    Database Error in model lstm_performance_metrics (models/marts/analytics/lstm_performance_metrics.sql)
[2025-05-11T04:18:06.408+0700] {subprocess.py:93} INFO -   column "actual_close" does not exist
[2025-05-11T04:18:06.408+0700] {subprocess.py:93} INFO -   LINE 23:         SUM(CASE WHEN actual_close IS NOT NULL THEN 1 ELSE 0...
[2025-05-11T04:18:06.409+0700] {subprocess.py:93} INFO -                                  ^
[2025-05-11T04:18:06.410+0700] {subprocess.py:93} INFO -   compiled code at target/run/idx_stock/models/marts/analytics/lstm_performance_metrics.sql
[2025-05-11T04:18:06.410+0700] {subprocess.py:93} INFO - [0m21:18:06
[2025-05-11T04:18:06.411+0700] {subprocess.py:93} INFO - [0m21:18:06  Done. PASS=2 WARN=0 ERROR=2 SKIP=0 TOTAL=4
[2025-05-11T04:18:07.942+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-11T04:18:07.943+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T04:18:07.963+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-11T04:18:07.970+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=bbca_lstm_prediction, task_id=run_lstm_dbt, run_id=scheduled__2025-05-08T11:30:00+00:00, execution_date=20250508T113000, start_date=20250510T211757, end_date=20250510T211807
[2025-05-11T04:18:07.987+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 111 for task run_lstm_dbt (Bash command failed. The command returned a non-zero exit code 1.; 368)
[2025-05-11T04:18:08.011+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-11T04:18:08.036+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T04:18:08.042+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
