[2025-05-11T04:10:47.516+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T04:10:47.557+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [None]>
[2025-05-11T04:10:47.567+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [None]>
[2025-05-11T04:10:47.568+0700] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2025-05-11T04:10:47.587+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_lstm_dbt> on 2025-05-08 11:30:00+00:00
[2025-05-11T04:10:47.599+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bbca_lstm_prediction', 'run_lstm_dbt', 'scheduled__2025-05-08T11:30:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/stock_predictions_bbca.py', '--cfg-path', '/tmp/tmp_pwhue0r']
[2025-05-11T04:10:47.604+0700] {standard_task_runner.py:91} INFO - Job 108: Subtask run_lstm_dbt
[2025-05-11T04:10:47.610+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2512) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-11T04:10:47.611+0700] {standard_task_runner.py:63} INFO - Started process 2532 to run task
[2025-05-11T04:10:47.687+0700] {task_command.py:426} INFO - Running <TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [running]> on host a61c3a2f78e1
[2025-05-11T04:10:47.816+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bbca_lstm_prediction' AIRFLOW_CTX_TASK_ID='run_lstm_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T11:30:00+00:00'
[2025-05-11T04:10:47.817+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T04:10:47.832+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-11T04:10:47.833+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt --select stg_stock_predictions fct_stock_predictions lstm_performance_metrics stock_prediction_dashboard']
[2025-05-11T04:10:47.848+0700] {subprocess.py:86} INFO - Output:
[2025-05-11T04:10:50.857+0700] {subprocess.py:93} INFO - [0m21:10:50  Running with dbt=1.9.4
[2025-05-11T04:10:51.288+0700] {subprocess.py:93} INFO - [0m21:10:51  Registered adapter: postgres=1.9.0
[2025-05-11T04:10:52.949+0700] {subprocess.py:93} INFO - [0m21:10:52  Found 14 models, 3 data tests, 6 sources, 434 macros
[2025-05-11T04:10:52.956+0700] {subprocess.py:93} INFO - [0m21:10:52
[2025-05-11T04:10:52.959+0700] {subprocess.py:93} INFO - [0m21:10:52  Concurrency: 4 threads (target='dev')
[2025-05-11T04:10:52.961+0700] {subprocess.py:93} INFO - [0m21:10:52
[2025-05-11T04:10:53.289+0700] {subprocess.py:93} INFO - [0m21:10:53  1 of 4 START sql view model public_staging.stg_stock_predictions ............... [RUN]
[2025-05-11T04:10:53.566+0700] {subprocess.py:93} INFO - [0m21:10:53  1 of 4 OK created sql view model public_staging.stg_stock_predictions .......... [[32mCREATE VIEW[0m in 0.27s]
[2025-05-11T04:10:53.574+0700] {subprocess.py:93} INFO - [0m21:10:53  2 of 4 START sql table model public_core.fct_stock_predictions ................. [RUN]
[2025-05-11T04:10:55.743+0700] {subprocess.py:93} INFO - [0m21:10:55  2 of 4 OK created sql table model public_core.fct_stock_predictions ............ [[32mSELECT 1[0m in 2.16s]
[2025-05-11T04:10:55.752+0700] {subprocess.py:93} INFO - [0m21:10:55  3 of 4 START sql table model public_analytics.lstm_performance_metrics ......... [RUN]
[2025-05-11T04:10:55.755+0700] {subprocess.py:93} INFO - [0m21:10:55  4 of 4 START sql table model public_analytics.stock_prediction_dashboard ....... [RUN]
[2025-05-11T04:10:55.894+0700] {subprocess.py:93} INFO - [0m21:10:55  3 of 4 ERROR creating sql table model public_analytics.lstm_performance_metrics  [[31mERROR[0m in 0.13s]
[2025-05-11T04:10:55.896+0700] {subprocess.py:93} INFO - [0m21:10:55  4 of 4 ERROR creating sql table model public_analytics.stock_prediction_dashboard  [[31mERROR[0m in 0.13s]
[2025-05-11T04:10:55.952+0700] {subprocess.py:93} INFO - [0m21:10:55
[2025-05-11T04:10:55.954+0700] {subprocess.py:93} INFO - [0m21:10:55  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 2.99 seconds (2.99s).
[2025-05-11T04:10:56.078+0700] {subprocess.py:93} INFO - [0m21:10:56
[2025-05-11T04:10:56.081+0700] {subprocess.py:93} INFO - [0m21:10:56  [31mCompleted with 2 errors, 0 partial successes, and 0 warnings:[0m
[2025-05-11T04:10:56.083+0700] {subprocess.py:93} INFO - [0m21:10:56
[2025-05-11T04:10:56.086+0700] {subprocess.py:93} INFO - [0m21:10:56    Database Error in model lstm_performance_metrics (models/marts/analytics/lstm_performance_metrics.sql)
[2025-05-11T04:10:56.087+0700] {subprocess.py:93} INFO -   column "actual_close" does not exist
[2025-05-11T04:10:56.088+0700] {subprocess.py:93} INFO -   LINE 23:         SUM(CASE WHEN actual_close IS NOT NULL THEN 1 ELSE 0...
[2025-05-11T04:10:56.089+0700] {subprocess.py:93} INFO -                                  ^
[2025-05-11T04:10:56.091+0700] {subprocess.py:93} INFO -   compiled code at target/run/idx_stock/models/marts/analytics/lstm_performance_metrics.sql
[2025-05-11T04:10:56.091+0700] {subprocess.py:93} INFO - [0m21:10:56
[2025-05-11T04:10:56.093+0700] {subprocess.py:93} INFO - [0m21:10:56    Database Error in model stock_prediction_dashboard (models/marts/analytics/stock_prediction_dashboard.sql)
[2025-05-11T04:10:56.093+0700] {subprocess.py:93} INFO -   column ld.predicted_close does not exist
[2025-05-11T04:10:56.094+0700] {subprocess.py:93} INFO -   LINE 66:         ld.predicted_close,
[2025-05-11T04:10:56.095+0700] {subprocess.py:93} INFO -                    ^
[2025-05-11T04:10:56.096+0700] {subprocess.py:93} INFO -   compiled code at target/run/idx_stock/models/marts/analytics/stock_prediction_dashboard.sql
[2025-05-11T04:10:56.097+0700] {subprocess.py:93} INFO - [0m21:10:56
[2025-05-11T04:10:56.099+0700] {subprocess.py:93} INFO - [0m21:10:56  Done. PASS=2 WARN=0 ERROR=2 SKIP=0 TOTAL=4
[2025-05-11T04:10:57.650+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-11T04:10:57.653+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T04:10:57.669+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-11T04:10:57.675+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=bbca_lstm_prediction, task_id=run_lstm_dbt, run_id=scheduled__2025-05-08T11:30:00+00:00, execution_date=20250508T113000, start_date=20250510T211047, end_date=20250510T211057
[2025-05-11T04:10:57.697+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 108 for task run_lstm_dbt (Bash command failed. The command returned a non-zero exit code 1.; 2532)
[2025-05-11T04:10:57.732+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-11T04:10:57.752+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T04:10:57.759+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
