[2025-05-11T02:55:33.352+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T02:55:33.403+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transformation.run_dbt_staging scheduled__2025-05-09T17:00:00+00:00 [queued]>
[2025-05-11T02:55:33.415+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transformation.run_dbt_staging scheduled__2025-05-09T17:00:00+00:00 [queued]>
[2025-05-11T02:55:33.416+0700] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2025-05-11T02:55:33.438+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_staging> on 2025-05-09 17:00:00+00:00
[2025-05-11T02:55:33.444+0700] {standard_task_runner.py:63} INFO - Started process 2431 to run task
[2025-05-11T02:55:33.447+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_transformation', 'run_dbt_staging', 'scheduled__2025-05-09T17:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/data_transformation.py', '--cfg-path', '/tmp/tmp2_mozzqs']
[2025-05-11T02:55:33.451+0700] {standard_task_runner.py:91} INFO - Job 35: Subtask run_dbt_staging
[2025-05-11T02:55:33.539+0700] {task_command.py:426} INFO - Running <TaskInstance: data_transformation.run_dbt_staging scheduled__2025-05-09T17:00:00+00:00 [running]> on host f94ba298fced
[2025-05-11T02:55:33.875+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_transformation' AIRFLOW_CTX_TASK_ID='run_dbt_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-09T17:00:00+00:00'
[2025-05-11T02:55:33.876+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T02:55:33.895+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-11T02:55:33.897+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt --select staging --exclude stg_stock_predictions model_performance_metrics']
[2025-05-11T02:55:33.907+0700] {subprocess.py:86} INFO - Output:
[2025-05-11T02:55:36.986+0700] {subprocess.py:93} INFO - [0m19:55:36  Running with dbt=1.9.4
[2025-05-11T02:55:37.479+0700] {subprocess.py:93} INFO - [0m19:55:37  Registered adapter: postgres=1.9.0
[2025-05-11T02:55:38.998+0700] {subprocess.py:93} INFO - [0m19:55:38  Encountered an error:
[2025-05-11T02:55:38.999+0700] {subprocess.py:93} INFO - Compilation Error
[2025-05-11T02:55:39.000+0700] {subprocess.py:93} INFO -   Model 'model.idx_stock.lstm_performance_metrics' (models/marts/analytics/lstm_performance_metrics.sql) depends on a source named 'public.model_performance_metrics' which was not found
[2025-05-11T02:55:40.646+0700] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-11T02:55:40.647+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T02:55:40.667+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-11T02:55:40.673+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_transformation, task_id=run_dbt_staging, run_id=scheduled__2025-05-09T17:00:00+00:00, execution_date=20250509T170000, start_date=20250510T195533, end_date=20250510T195540
[2025-05-11T02:55:40.693+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task run_dbt_staging (Bash command failed. The command returned a non-zero exit code 2.; 2431)
[2025-05-11T02:55:40.709+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-11T02:55:40.748+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T02:55:40.755+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
