[2025-05-11T03:02:31.282+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T03:02:31.350+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transformation.run_dbt_staging scheduled__2025-05-09T17:00:00+00:00 [queued]>
[2025-05-11T03:02:31.364+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transformation.run_dbt_staging scheduled__2025-05-09T17:00:00+00:00 [queued]>
[2025-05-11T03:02:31.365+0700] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2025-05-11T03:02:31.389+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_staging> on 2025-05-09 17:00:00+00:00
[2025-05-11T03:02:31.395+0700] {standard_task_runner.py:63} INFO - Started process 2867 to run task
[2025-05-11T03:02:31.399+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_transformation', 'run_dbt_staging', 'scheduled__2025-05-09T17:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/data_transformation.py', '--cfg-path', '/tmp/tmp29jtd8hc']
[2025-05-11T03:02:31.404+0700] {standard_task_runner.py:91} INFO - Job 43: Subtask run_dbt_staging
[2025-05-11T03:02:31.513+0700] {task_command.py:426} INFO - Running <TaskInstance: data_transformation.run_dbt_staging scheduled__2025-05-09T17:00:00+00:00 [running]> on host f94ba298fced
[2025-05-11T03:02:31.884+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_transformation' AIRFLOW_CTX_TASK_ID='run_dbt_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-09T17:00:00+00:00'
[2025-05-11T03:02:31.885+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T03:02:31.911+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-11T03:02:31.913+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt --select marts.analytics --exclude lstm_performance_metrics model_performance_metrics stock_prediction_dashboard']
[2025-05-11T03:02:31.926+0700] {subprocess.py:86} INFO - Output:
[2025-05-11T03:02:36.505+0700] {subprocess.py:93} INFO - [0m20:02:36  Running with dbt=1.9.4
[2025-05-11T03:02:37.060+0700] {subprocess.py:93} INFO - [0m20:02:37  Registered adapter: postgres=1.9.0
[2025-05-11T03:02:38.963+0700] {subprocess.py:93} INFO - [0m20:02:38  Encountered an error:
[2025-05-11T03:02:38.964+0700] {subprocess.py:93} INFO - Compilation Error
[2025-05-11T03:02:38.964+0700] {subprocess.py:93} INFO -   Model 'model.idx_stock.stg_stock_predictions' (models/staging/stg_stock_predictions.sql) depends on a source named 'public.stock_predictions' which was not found
[2025-05-11T03:02:40.604+0700] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-11T03:02:40.605+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T03:02:40.622+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-11T03:02:40.627+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_transformation, task_id=run_dbt_staging, run_id=scheduled__2025-05-09T17:00:00+00:00, execution_date=20250509T170000, start_date=20250510T200231, end_date=20250510T200240
[2025-05-11T03:02:40.651+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task run_dbt_staging (Bash command failed. The command returned a non-zero exit code 2.; 2867)
[2025-05-11T03:02:40.679+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-11T03:02:40.712+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T03:02:40.718+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
