[2025-05-11T02:33:17.919+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T02:33:17.979+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bulk_stock_loader.trigger_transformation manual__2025-05-10T19:14:26.076860+00:00 [queued]>
[2025-05-11T02:33:17.994+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bulk_stock_loader.trigger_transformation manual__2025-05-10T19:14:26.076860+00:00 [queued]>
[2025-05-11T02:33:17.995+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-11T02:33:18.017+0700] {taskinstance.py:2330} INFO - Executing <Task(TriggerDagRunOperator): trigger_transformation> on 2025-05-10 19:14:26.076860+00:00
[2025-05-11T02:33:18.029+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bulk_stock_loader', 'trigger_transformation', 'manual__2025-05-10T19:14:26.076860+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/bulk_load_all_excel.py', '--cfg-path', '/tmp/tmpne9lmrmk']
[2025-05-11T02:33:18.033+0700] {standard_task_runner.py:91} INFO - Job 6: Subtask trigger_transformation
[2025-05-11T02:33:18.037+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1011) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-11T02:33:18.039+0700] {standard_task_runner.py:63} INFO - Started process 1029 to run task
[2025-05-11T02:33:18.133+0700] {task_command.py:426} INFO - Running <TaskInstance: bulk_stock_loader.trigger_transformation manual__2025-05-10T19:14:26.076860+00:00 [running]> on host f94ba298fced
[2025-05-11T02:33:18.267+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bulk_stock_loader' AIRFLOW_CTX_TASK_ID='trigger_transformation' AIRFLOW_CTX_EXECUTION_DATE='2025-05-10T19:14:26.076860+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-10T19:14:26.076860+00:00'
[2025-05-11T02:33:18.269+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T02:33:20.818+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.operators.bigquery.BigQueryConsoleLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 47, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 67, in <module>
    from airflow.providers.google.cloud.utils.credentials_provider import _get_scopes
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 37, in <module>
    from airflow.providers.google.cloud._internal_client.secret_manager_client import _SecretManagerClient
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/_internal_client/secret_manager_client.py", line 24, in <module>
    from google.cloud.secretmanager_v1 import SecretManagerServiceClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/__init__.py", line 21, in <module>
    from .services.secret_manager_service import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/__init__.py", line 16, in <module>
    from .async_client import SecretManagerServiceAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/async_client.py", line 52, in <module>
    from google.cloud.secretmanager_v1.services.secret_manager_service import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/pagers.py", line 27, in <module>
    from google.cloud.secretmanager_v1.types import resources, service
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/types/__init__.py", line 16, in <module>
    from .resources import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/types/resources.py", line 22, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:20.835+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.operators.bigquery.BigQueryConsoleIndexableLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 47, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 67, in <module>
    from airflow.providers.google.cloud.utils.credentials_provider import _get_scopes
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 37, in <module>
    from airflow.providers.google.cloud._internal_client.secret_manager_client import _SecretManagerClient
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/_internal_client/secret_manager_client.py", line 24, in <module>
    from google.cloud.secretmanager_v1 import SecretManagerServiceClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/__init__.py", line 21, in <module>
    from .services.secret_manager_service import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/__init__.py", line 16, in <module>
    from .async_client import SecretManagerServiceAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/async_client.py", line 52, in <module>
    from google.cloud.secretmanager_v1.services.secret_manager_service import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/pagers.py", line 27, in <module>
    from google.cloud.secretmanager_v1.types import resources, service
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/types/__init__.py", line 16, in <module>
    from .resources import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/secretmanager_v1/types/resources.py", line 22, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:20.917+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.operators.dataproc_metastore.DataprocMetastoreDetailedLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/dataproc_metastore.py", line 27, in <module>
    from google.cloud.metastore_v1 import MetadataExport, MetadataManagementActivity
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/__init__.py", line 21, in <module>
    from .services.dataproc_metastore import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/services/dataproc_metastore/__init__.py", line 16, in <module>
    from .async_client import DataprocMetastoreAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/services/dataproc_metastore/async_client.py", line 55, in <module>
    from google.cloud.metastore_v1.services.dataproc_metastore import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/services/dataproc_metastore/pagers.py", line 27, in <module>
    from google.cloud.metastore_v1.types import metastore
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/types/__init__.py", line 16, in <module>
    from .metastore import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/types/metastore.py", line 24, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:20.928+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.operators.dataproc_metastore.DataprocMetastoreLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/dataproc_metastore.py", line 27, in <module>
    from google.cloud.metastore_v1 import MetadataExport, MetadataManagementActivity
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/__init__.py", line 21, in <module>
    from .services.dataproc_metastore import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/services/dataproc_metastore/__init__.py", line 16, in <module>
    from .async_client import DataprocMetastoreAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/services/dataproc_metastore/async_client.py", line 55, in <module>
    from google.cloud.metastore_v1.services.dataproc_metastore import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/services/dataproc_metastore/pagers.py", line 27, in <module>
    from google.cloud.metastore_v1.types import metastore
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/types/__init__.py", line 16, in <module>
    from .metastore import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/metastore_v1/types/metastore.py", line 24, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:20.974+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.operators.cloud_composer.CloudComposerEnvironmentLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/cloud_composer.py", line 25, in <module>
    from google.cloud.orchestration.airflow.service_v1 import ImageVersion
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/__init__.py", line 23, in <module>
    from .services.environments import EnvironmentsAsyncClient, EnvironmentsClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/services/environments/__init__.py", line 16, in <module>
    from .async_client import EnvironmentsAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/services/environments/async_client.py", line 54, in <module>
    from google.cloud.orchestration.airflow.service_v1.services.environments import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/services/environments/pagers.py", line 27, in <module>
    from google.cloud.orchestration.airflow.service_v1.types import environments
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/types/__init__.py", line 16, in <module>
    from .environments import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/types/environments.py", line 22, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:20.985+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.operators.cloud_composer.CloudComposerEnvironmentsLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/cloud_composer.py", line 25, in <module>
    from google.cloud.orchestration.airflow.service_v1 import ImageVersion
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/__init__.py", line 23, in <module>
    from .services.environments import EnvironmentsAsyncClient, EnvironmentsClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/services/environments/__init__.py", line 16, in <module>
    from .async_client import EnvironmentsAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/services/environments/async_client.py", line 54, in <module>
    from google.cloud.orchestration.airflow.service_v1.services.environments import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/services/environments/pagers.py", line 27, in <module>
    from google.cloud.orchestration.airflow.service_v1.types import environments
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/types/__init__.py", line 16, in <module>
    from .environments import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/orchestration/airflow/service_v1/types/environments.py", line 22, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:21.079+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.links.kubernetes_engine.KubernetesEngineClusterLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/links/kubernetes_engine.py", line 22, in <module>
    from google.cloud.container_v1.types import Cluster
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/__init__.py", line 21, in <module>
    from .services.cluster_manager import ClusterManagerAsyncClient, ClusterManagerClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/__init__.py", line 16, in <module>
    from .async_client import ClusterManagerAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/async_client.py", line 49, in <module>
    from google.cloud.container_v1.services.cluster_manager import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/pagers.py", line 27, in <module>
    from google.cloud.container_v1.types import cluster_service
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/types/__init__.py", line 16, in <module>
    from .cluster_service import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/types/cluster_service.py", line 25, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:21.095+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.links.kubernetes_engine.KubernetesEnginePodLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/links/kubernetes_engine.py", line 22, in <module>
    from google.cloud.container_v1.types import Cluster
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/__init__.py", line 21, in <module>
    from .services.cluster_manager import ClusterManagerAsyncClient, ClusterManagerClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/__init__.py", line 16, in <module>
    from .async_client import ClusterManagerAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/async_client.py", line 49, in <module>
    from google.cloud.container_v1.services.cluster_manager import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/pagers.py", line 27, in <module>
    from google.cloud.container_v1.types import cluster_service
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/types/__init__.py", line 16, in <module>
    from .cluster_service import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/types/cluster_service.py", line 25, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:21.107+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.links.kubernetes_engine.KubernetesEngineJobLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/links/kubernetes_engine.py", line 22, in <module>
    from google.cloud.container_v1.types import Cluster
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/__init__.py", line 21, in <module>
    from .services.cluster_manager import ClusterManagerAsyncClient, ClusterManagerClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/__init__.py", line 16, in <module>
    from .async_client import ClusterManagerAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/async_client.py", line 49, in <module>
    from google.cloud.container_v1.services.cluster_manager import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/pagers.py", line 27, in <module>
    from google.cloud.container_v1.types import cluster_service
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/types/__init__.py", line 16, in <module>
    from .cluster_service import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/types/cluster_service.py", line 25, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:21.119+0700] {providers_manager.py:291} WARNING - Exception when importing '***.providers.google.cloud.links.kubernetes_engine.KubernetesEngineWorkloadsLink' from 'apache-***-providers-google' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers_manager.py", line 322, in _correctness_check
    imported_class = import_string(class_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/links/kubernetes_engine.py", line 22, in <module>
    from google.cloud.container_v1.types import Cluster
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/__init__.py", line 21, in <module>
    from .services.cluster_manager import ClusterManagerAsyncClient, ClusterManagerClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/__init__.py", line 16, in <module>
    from .async_client import ClusterManagerAsyncClient
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/async_client.py", line 49, in <module>
    from google.cloud.container_v1.services.cluster_manager import pagers
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/services/cluster_manager/pagers.py", line 27, in <module>
    from google.cloud.container_v1.types import cluster_service
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/types/__init__.py", line 16, in <module>
    from .cluster_service import (
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/container_v1/types/cluster_service.py", line 25, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/__init__.py", line 15, in <module>
    from .enums import Enum
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/enums.py", line 19, in <module>
    from proto import _file_info
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/_file_info.py", line 24, in <module>
    from proto.marshal.rules.message import MessageRule
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/__init__.py", line 15, in <module>
    from .marshal import Marshal
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/marshal.py", line 25, in <module>
    from proto.marshal import compat
  File "/home/airflow/.local/lib/python3.12/site-packages/proto/marshal/compat.py", line 43, in <module>
    map_composite_types += (_message.MessageMapContainer,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'
[2025-05-11T02:33:22.635+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:175 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.638+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:222 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.642+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:1151 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.645+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:1248 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.647+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:1271 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.650+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:1406 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.652+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:1439 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.653+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:1495 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.656+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:1683 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.658+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:1750 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.661+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:2025 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.663+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:2110 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.666+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:2407 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.668+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:2468 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.674+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:3987 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.677+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:4096 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.679+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:4127 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.681+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:4186 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.683+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:4225 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.685+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:4275 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.689+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:5209 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.692+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:5265 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.694+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:5302 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.696+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:5358 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.701+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:6437 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.703+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:6497 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.705+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:6538 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.707+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:6588 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.710+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:7023 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.712+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:7096 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.714+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:7267 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.717+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:7333 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.719+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:7378 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.721+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:7440 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.725+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:8222 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.727+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:8282 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.729+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:8322 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.731+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:8368 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.736+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:9475 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.738+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:9531 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.742+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:10532 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.744+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:10588 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.746+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:10625 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.748+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:10680 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.752+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:10923 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.755+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:10979 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.756+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:11016 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.758+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:11072 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.760+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:11231 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.762+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:11282 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.764+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:11420 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.766+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:11477 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.770+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:12300 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.772+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:12383 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.774+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:12439 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.775+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:12524 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.778+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:13019 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.780+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:13090 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.782+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:13139 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.784+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:13200 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.788+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:13886 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.790+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:13941 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.791+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:13977 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.793+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:14026 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.795+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:14318 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.798+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:14388 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.800+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:14436 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.802+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:14492 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.804+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:14744 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.805+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:14810 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.809+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:15415 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.810+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:15482 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.812+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:15527 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.814+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:15578 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.817+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:15897 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.819+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:15953 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.822+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:16617 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.824+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:16674 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.826+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:16712 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.828+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:16780 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.830+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:16932 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.832+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:16988 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.834+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:17025 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.836+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:17090 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.838+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:17228 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.840+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:17284 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.849+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:20234 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.851+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:20289 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.854+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:20862 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.856+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:20921 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.858+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:20960 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.860+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:21014 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.871+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:21316 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.873+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:21377 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.875+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:21418 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.877+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:21478 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.879+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:21612 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.881+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:21668 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.885+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:22155 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.887+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:22218 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.890+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:22559 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.892+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:22626 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.894+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:22671 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.895+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:22722 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.898+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:23061 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.901+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:23128 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.902+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:23173 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.904+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:23224 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.907+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:23511 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.909+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:23567 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.912+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:23968 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.914+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:24018 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.920+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:25343 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.922+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:25398 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.924+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:25434 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.926+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:25485 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.931+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:26723 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.933+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:26779 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.936+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:27121 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.938+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:27177 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.941+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:27461 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.943+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:27517 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.946+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:28053 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.949+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:28109 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.952+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:28536 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.954+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:28592 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.957+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:28932 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.959+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:28982 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.966+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:30727 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.969+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:30783 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.972+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:31296 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.974+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:31344 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.977+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:31617 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.978+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:31673 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.982+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:32120 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.984+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:32176 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.986+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:32339 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.989+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:32395 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.990+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:32432 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.992+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:32487 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.997+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:33502 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:22.999+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:33558 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.002+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:33869 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.004+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:33928 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.006+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:33967 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.008+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:34021 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.012+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:34739 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.014+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:34806 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.016+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:34852 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.018+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:34908 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.026+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:36915 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.028+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:36971 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.031+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:37417 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.033+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:37473 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.036+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:37845 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.038+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:37901 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.040+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:38208 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.042+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:38264 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.044+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:38301 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.046+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:38351 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.049+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:38690 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.051+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:38758 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.054+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:39141 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.056+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:39192 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.058+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:39419 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.060+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:39487 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.062+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:39683 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.064+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:39738 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.067+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:40019 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.069+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:40084 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.073+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:41138 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.075+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:41196 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.077+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:41359 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.079+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:41415 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.081+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:41452 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.084+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:41507 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.087+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:41875 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.090+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:41947 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.106+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:42441 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.108+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:42497 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.109+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:42534 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.111+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:42590 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.113+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:42627 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.116+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:42692 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.118+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:43020 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.120+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:43079 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.123+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:43118 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.124+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:43168 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.127+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:43514 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.129+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:43573 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.130+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:43612 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.133+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:43666 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.135+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:43989 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.137+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:44045 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.139+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:44386 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.141+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:44442 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.147+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:45003 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.150+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:45058 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.152+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:45444 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.154+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:45499 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.157+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:46042 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.159+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:46098 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.162+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:46702 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.165+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:46758 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.167+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:47000 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.169+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:47050 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.172+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:47648 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.174+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:47704 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.177+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:48113 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.179+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:48190 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.181+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:48244 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.183+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:48321 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.188+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:49499 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.190+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:49555 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.193+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:49932 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.195+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50002 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.197+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50052 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.199+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50107 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.202+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50379 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.204+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50449 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.206+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50499 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.207+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50554 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.209+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50590 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.211+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50660 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.213+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50710 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.215+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:50770 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.218+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51046 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.220+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51116 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.221+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51166 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.223+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51226 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.226+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51485 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.227+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51540 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.230+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51787 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.232+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51851 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.234+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51895 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.236+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:51958 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.238+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:52212 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.240+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:52275 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.242+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:52463 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.244+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:52532 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.247+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:53040 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.249+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:53111 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.252+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:53334 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.254+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:53407 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.257+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:53961 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.259+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:54059 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.261+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:54322 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.263+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:54398 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.267+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:55022 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.269+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:55078 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.272+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:55310 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.273+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:55365 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.277+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:56196 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.279+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:56248 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.282+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:56508 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.284+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:56564 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.287+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:57087 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.289+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:57147 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.291+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:57187 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.292+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:57237 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.295+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:57560 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.297+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:57620 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.299+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:57660 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.302+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:57710 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.308+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59106 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.310+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59162 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.312+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59316 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.314+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59396 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.316+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59452 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.319+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59535 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.320+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59594 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.322+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59677 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.324+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59733 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.326+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:59818 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.330+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:60639 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.333+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:60722 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.334+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:60778 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.336+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:60863 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.339+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:61167 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.341+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:61250 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.342+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:61306 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.344+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:61387 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.347+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:61696 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.349+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:61752 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.352+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:61954 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.354+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:61992 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.357+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:62660 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.359+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:62715 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.364+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:63882 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.366+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:63946 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.370+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:64582 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.372+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:64674 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.374+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:64940 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.376+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65014 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.378+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65117 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.381+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65199 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.383+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65385 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.385+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65441 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.388+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65874 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.390+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65950 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.392+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66003 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.394+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66087 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.397+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66686 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.400+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66779 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.402+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66918 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.404+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66964 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.410+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:67735 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.412+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:67791 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.416+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:68043 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.418+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:68097 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.420+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:68532 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:23.422+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:68588 SyntaxWarning: invalid escape sequence '\d'
[2025-05-11T02:33:24.070+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T02:33:24.086+0700] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bulk_stock_loader, task_id=trigger_transformation, run_id=manual__2025-05-10T19:14:26.076860+00:00, execution_date=20250510T191426, start_date=20250510T193317, end_date=20250510T193324
[2025-05-11T02:33:24.136+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-11T02:33:24.157+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T02:33:24.163+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
